/*
 * Automatically generated C config: don't edit
 * LTIB version: 9.1.1
 */
#define AUTOCONF_INCLUDED
#define CONFIG_CONFIG_TITLE "LTIB: NXP LPX3XXX on the Embedded Artists LPC3250 OEM Board"
#define CONFIG_CPU "LPC3XXX"
#define CONFIG_PLATFORM_COMMENT "Embedded Artists LPC3250 OEM Board with the NXP LPC32XX SoC"
#define CONFIG_VENDOR "NXP"
#define CONFIG_PLATFORM "ea3250"
#define CONFIG_GNUTARCH "arm"
#define CONFIG_LINTARCH "arm"
#define CONFIG_CFGHOST "arm-linux"

/*
 * LTIB settings
 */

/*
 * System features
 */
#define CONFIG_FEAT_CACHE_RPMS 1
#define CONFIG_ENDIAN "little"

/*
 * Choose the target C library type
 */
#define CONFIG_GLIBC 1
#undef CONFIG_UCLIBC
#define CONFIG_CHOICE_BASE_LIBS 1
#undef CONFIG_CHOICE_GLIBC
#undef CONFIG_CHOICE_UCLIBC
#undef CONFIG_LIBC_NONE
#undef CONFIG_PKG_GLIBC
#undef CONFIG_PKG_UCLIBC

/*
 * Toolchain component options
 */
#define CONFIG_PKG_BASE_LIBS 1
#define CONFIG_PKG_LIBC_WANT_SHARED_LIBS 1
#define CONFIG_PKG_LIBC_WANT_CRT_FILES 1
#undef CONFIG_PKG_LIBC_WANT_HEADERS1
#undef CONFIG_PKG_LIBC_WANT_STATIC_LIBS
#undef CONFIG_PKG_LIBC_WANT_C_LOCALES
#define CONFIG_PKG_CXX_WANT_SHARED_LIBS 1
#define CONFIG_PKG_CXX_WANT_HEADERS 1
#define CONFIG_PKG_CXX_WANT_STATIC_LIBS 1
#define CONFIG_PKG_GCC_WANT_LIBGCC_SHARED 1
#define CONFIG_DYNAMIC_LINKER "/lib/ld.so.1"
#define CONFIG_SYS_WANT_MMU 1
#define CONFIG_SYS_WANT_SHARED 1

/*
 * Choose your toolchain
 */
#define CONFIG_TOOLCHAIN_ARMEABI_GLIBC1 1
#undef CONFIG_TOOLCHAIN2
#undef CONFIG_TOOLCHAIN_CUSTOM
#define CONFIG_TOOLCHAIN "tc-fsl-x86lnx-armeabi-nptl-4.1.2-3.i386.rpm"
#define CONFIG_TOOLCHAIN_PATH "/opt/freescale/usr/local/gcc-4.1.2-glibc-2.5-nptl-3/arm-none-linux-gnueabi"
#define CONFIG_TOOLCHAIN_PREFIX "arm-none-linux-gnueabi-"
#define CONFIG_TOOLCHAIN_CFLAGS ""

/*
 * Bootloader
 */
#undef CONFIG_BOOTLOADER1
#define CONFIG_BOOTLOADER_NONE 1

/*
 * Choose your Kernel
 */
#define CONFIG_EA_KERNEL_2_6_27_8 1
#undef CONFIG_KERNEL_DIR_BUILD
#undef CONFIG_KERNEL_NONE
#define CONFIG_PKG_KERNEL "kernel-2.6.27.8-lpc32xx"
#define CONFIG_PKG_KERNEL_FORCE 1
#undef CONFIG_PKG_KERNEL_WANT_CSCOPE
#define CONFIG_PKG_KERNEL_PRECONFIG "linux-2.6.27.8-ea3250.config"
#define CONFIG_PKG_KERNEL_WANT_HEADERS 1
#define CONFIG_PKG_KERNEL_WANT_CF 1
#define CONFIG_PKG_KERNEL_LEAVESRC 1
#define CONFIG_SYSCFG_KTARG "uImage"
#define CONFIG_SYSCFG_BOOT_KERNEL "arch/arm/boot/uImage"
#define CONFIG_DISTRO "dist/lfs-5.1"

/*
 * Package selection
 */

/*
 * Package list
 */

/*
 * Platform specific package selection
 */

/*
 * Common package selection list
 */
#undef CONFIG_PKG_ASTERISK
#undef CONFIG_PKG_ATK
#define CONFIG_PKG_AUTOCONF 1
#define CONFIG_PKG_AUTOMAKE 1
#define CONFIG_PKG_ALSA_LIB 1
#define CONFIG_PKG_ALSA_UTILS 1
#define CONFIG_PKG_BASH 1
#undef CONFIG_PKG_BASH_WANT_NO_SH_SYMLINK
#undef CONFIG_PKG_BIND
#define CONFIG_PKG_BINUTILS 1
#undef CONFIG_PKG_BINUTILS_BUILD_DOCS
#define CONFIG_PKG_BISON 1
#undef CONFIG_PKG_BLUEZ_HCIDUMP
#undef CONFIG_PKG_BLUEZ_LIBS
#undef CONFIG_PKG_BLUEZ_UTILS
#define CONFIG_PKG_BOA 1
#undef CONFIG_PKG_BONNIE_PLUS_PLUS
#undef CONFIG_PKG_BRIDGE_UTILS
#define CONFIG_PKG_BUSYBOX 1
#define CONFIG_PKG_BUSYBOX_PRECONFIG "busybox.config"
#undef CONFIG_PKG_BUSYBOX_WANT_CF
#undef CONFIG_PKG_BZIP2
#undef CONFIG_PKG_CAIRO
#undef CONFIG_PKG_CAN4LINUX
#undef CONFIG_PKG_CANTEST
#undef CONFIG_PKG_CCACHE
#undef CONFIG_PKG_CGICC
#undef CONFIG_PKG_CLAMAV
#undef CONFIG_PKG_CONNTRACK_TOOLS
#define CONFIG_PKG_COREUTILS 1
#undef CONFIG_PKG_CPIO
#undef CONFIG_PKG_CPUFREQUTILS
#undef CONFIG_PKG_CRACKLIB
#undef CONFIG_PKG_CRAMFS
#undef CONFIG_PKG_CURL
#undef CONFIG_PKG_DAEMONIZER
#define CONFIG_PKG_DBUS 1
#undef CONFIG_PKG_DEVMEM2
#undef CONFIG_PKG_DHCP
#undef CONFIG_PKG_DB1
#undef CONFIG_PKG_DBG
#undef CONFIG_PKG_DEV
#undef CONFIG_PKG_MDEV
#define CONFIG_PKG_UDEV 1
#define CONFIG_PKG_UDEV_WANT_AUTOMOUNT 1
#define CONFIG_PKG_UDEV_WANT_NON_RAID 1
#undef CONFIG_PKG_UDEV_WANT_IMX
#undef CONFIG_PKG_DEVFSD
#undef CONFIG_PKG_DEV_NONE
#undef CONFIG_PKG_DIFFUTILS
#define CONFIG_PKG_DILLO2 1
#undef CONFIG_PKG_DIRECTFB
#undef CONFIG_PKG_DISTCC
#define CONFIG_PKG_DOSFSTOOLS 1
#define CONFIG_PKG_DROPBEAR 1
#define CONFIG_PKG_DROPBEAR_WANT_URANDOM_DEV 1
#define CONFIG_PKG_DROPBEAR_WANT_NO_REV_DNS 1
#define CONFIG_PKG_DROPBEAR_WANT_NO_X11FWD 1
#undef CONFIG_PKG_DROPBEAR_WANT_HACKABLE_KEY

/*
 * dtc
 */
#undef CONFIG_DTC
#undef CONFIG_PKG_DTC_WANT_FDT
#define CONFIG_PKG_E2FSPROGS 1
#undef CONFIG_PKG_ED
#define CONFIG_PKG_ETHTOOL 1
#undef CONFIG_PKG_EVTEST
#define CONFIG_PKG_EXPAT 1
#undef CONFIG_PKG_FAAD2
#undef CONFIG_PKG_FAKEROOT
#define CONFIG_PKG_FAKE_PROVIDES 1
#undef CONFIG_PKG_FARSIGHT
#undef CONFIG_PKG_FBPAN
#undef CONFIG_PKG_FBSET
#undef CONFIG_PKG_FBV
#undef CONFIG_PKG_FFMPEG
#undef CONFIG_PKG_FINDUTILS
#undef CONFIG_PKG_FLEX
#define CONFIG_PKG_FLTK2 1
#undef CONFIG_PKG_FONTCONFIG
#define CONFIG_PKG_FREETYPE 1
#define CONFIG_PKG_GAWK 1
#undef CONFIG_PKG_GDBM
#undef CONFIG_PKG_GDB
#undef CONFIG_PKG_GENEXT2FS
#undef CONFIG_PKG_GENROMFS
#undef CONFIG_PKG_GEN_INIT_CPIO
#undef CONFIG_PKG_GETTEXT
#define CONFIG_PKG_GIFLIB 1
#undef CONFIG_PKG_GIT
#undef CONFIG_PKG_GLIB2
#undef CONFIG_PKG_GMP
#undef CONFIG_PKG_GPSD
#undef CONFIG_PKG_GREP
#undef CONFIG_PKG_GROFF
#undef CONFIG_PKG_GSTREAMER_CORE
#undef CONFIG_PKG_GST_PLUGINS_FARSIGHT
#undef CONFIG_PKG_GTK2
#undef CONFIG_PKG_GTKWEBCAM
#undef CONFIG_PKG_HDPARM
#undef CONFIG_PKG_HELLOWORLD
#undef CONFIG_PKG_HELLOWORLD_MOD
#undef CONFIG_PKG_HESIOD
#define CONFIG_PKG_HOTPLUG 1
#undef CONFIG_PKG_HTTPD
#undef CONFIG_PKG_I2C_TOOLS
#undef CONFIG_PKG_IOZONE
#undef CONFIG_PKG_IPROUTE
#define CONFIG_PKG_INETUTILS 1
#undef CONFIG_PKG_IPERF
#undef CONFIG_PKG_OPENSWAN
#undef CONFIG_PKG_STRONGSWAN
#define CONFIG_PKG_IPSEC_SUITE_NONE 1
#undef CONFIG_PKG_IPSEC_TOOLS
#undef CONFIG_PKG_IPSECADM
#undef CONFIG_PKG_IPTABLES
#undef CONFIG_PKG_IPUTILS
#undef CONFIG_PKG_IRATTACH
#undef CONFIG_PKG_IRDADUMP
#undef CONFIG_PKG_JSON_C
#undef CONFIG_PKG_KBD
#undef CONFIG_PKG_KEYFUZZ
#undef CONFIG_PKG_KRB5
#undef CONFIG_PKG_LESS
#undef CONFIG_PKG_LFS_UTILS
#undef CONFIG_PKG_LIBDAEMON
#undef CONFIG_PKG_LIBERATION_FONTS
#undef CONFIG_PKG_LIBICONV
#undef CONFIG_PKG_LIBID3TAG
#undef CONFIG_PKG_LIBMAD
#undef CONFIG_PKG_LIBMPEG2
#undef CONFIG_PKG_LIBNETFILTER_CONNTRACK
#undef CONFIG_PKG_LIBNFNETLINK
#define CONFIG_PKG_LIBJPEG 1
#undef CONFIG_PKG_LIBELF
#undef CONFIG_PKG_LIBFAKEKEY
#undef CONFIG_PKG_LIBNET
#undef CONFIG_PKG_LIBPCAP
#define CONFIG_PKG_LIBPNG 1
#undef CONFIG_PKG_LIBOGG
#undef CONFIG_PKG_LIBOIL
#define CONFIG_PKG_LIBTERMCAP 1
#undef CONFIG_PKG_LIBTHEORA
#undef CONFIG_PKG_LIBTIFF
#undef CONFIG_PKG_LIBTOOL
#define CONFIG_PKG_LIBUSB 1
#undef CONFIG_PKG_LIBV4L
#undef CONFIG_PKG_LIBVORBIS
#undef CONFIG_PKG_LIBXML2
#undef CONFIG_PKG_LIBXML_PLUS_PLUS
#undef CONFIG_PKG_LIBXSLT
#undef CONFIG_PKG_LINUX_ATM
#undef CONFIG_PKG_LINUX_WLAN
#undef CONFIG_PKG_MPFR
#undef CONFIG_PKG_LKC
#undef CONFIG_PKG_LOGROTATE
#undef CONFIG_PKG_LTP
#undef CONFIG_PKG_LMBENCH
#undef CONFIG_PKG_LM_SENSORS
#undef CONFIG_PKG_LRZSZ
#define CONFIG_PKG_LZO 1
#define CONFIG_PKG_M4 1
#undef CONFIG_PKG_MADPLAY
#undef CONFIG_PKG_MAKE
#undef CONFIG_PKG_MAN
#undef CONFIG_PKG_MDADM
#define CONFIG_PKG_MERGE 1
#undef CONFIG_PKG_MICROWINDOWS
#define CONFIG_PKG_MINICOM 1
#define CONFIG_PKG_MODEPS 1
#undef CONFIG_PKG_MODUTILS
#undef CONFIG_PKG_MODULE_INIT_TOOLS
#define CONFIG_MODUTILS_NONE 1
#undef CONFIG_PKG_MPLAYER
#undef CONFIG_PKG_MP3PLAY
#define CONFIG_PKG_MTD_UTILS 1
#undef CONFIG_PKG_MUX_SERVER
#undef CONFIG_PKG_MYSQL
#define CONFIG_PKG_NCURSES 1
#define CONFIG_PKG_NCURSES_WANT_REDUCED_SET 1
#undef CONFIG_PKG_NET_SNMP
#undef CONFIG_PKG_NET_TOOLS
#undef CONFIG_PKG_NETCAT
#undef CONFIG_PKG_NETPERF
#undef CONFIG_PKG_NFS_UTILS
#undef CONFIG_PKG_NSS_MDNS
#undef CONFIG_PKG_NTPCLIENT
#undef CONFIG_PKG_OPENOBEX
#undef CONFIG_PKG_OPENSSH
#undef CONFIG_PKG_OPENSSL
#undef CONFIG_PKG_OPROFILE
#undef CONFIG_PKG_PANGO
#undef CONFIG_PKG_PATCH
#undef CONFIG_PKG_PCIUTILS
#undef CONFIG_PKG_PCMCIAUTILS
#undef CONFIG_PKG_PCRE
#undef CONFIG_PKG_PERL
#undef CONFIG_PKG_PHP
#undef CONFIG_PKG_PIDENTD
#undef CONFIG_PKG_PKGCONFIG
#undef CONFIG_PKG_PLAY
#undef CONFIG_PKG_POPT
#undef CONFIG_PKG_PORTMAP
#undef CONFIG_PKG_PPP
#undef CONFIG_PKG_PROCINFO
#define CONFIG_PKG_PROCPS 1
#undef CONFIG_PKG_PSMISC
#undef CONFIG_PKG_PYTHON

/*
 * Qtopia
 */
#define CONFIG_QTOPIA_NONE 1
#undef CONFIG_PKG_QTOPIA
#undef CONFIG_PKG_QTOPIA_4

/*
 * Applications
 */

/*
 * Settings applications
 */
#undef CONFIG_PKG_READLINE
#undef CONFIG_PKG_RPM
#undef CONFIG_PKG_RNG_TOOLS
#undef CONFIG_PKG_RSYNC
#undef CONFIG_PKG_RT_TESTS
#undef CONFIG_PKG_RTCTEST
#undef CONFIG_PKG_SAMBA
#undef CONFIG_PKG_SASH
#undef CONFIG_PKG_SCHEDUTILS
#undef CONFIG_PKG_SCREEN
#undef CONFIG_PKG_SDL
#undef CONFIG_PKG_SED
#undef CONFIG_PKG_SEQ
#undef CONFIG_PKG_SETSERIAL
#undef CONFIG_PKG_SIMICSFS_MOD
#define CONFIG_PKG_SKELL 1
#undef CONFIG_PKG_SKELL_WANT_TERMINFO
#undef CONFIG_PKG_SPARSE
#undef CONFIG_PKG_STATSERIAL
#undef CONFIG_PKG_SQLITE
#undef CONFIG_PKG_STRACE
#define CONFIG_PKG_SYSCONFIG 1
#undef CONFIG_PKG_SYSFSUTILS
#undef CONFIG_PKG_SYSKLOGD
#undef CONFIG_PKG_SYSSTAT
#undef CONFIG_PKG_SYSVINIT
#define CONFIG_PKG_TAR 1
#undef CONFIG_PKG_TCLAP
#undef CONFIG_PKG_TCPDUMP
#undef CONFIG_PKG_TCP_WRAPPERS
#define CONFIG_PKG_TERMCAP 1
#undef CONFIG_PKG_TEXINFO
#undef CONFIG_PKG_TIME
#undef CONFIG_PKG_TIMEZONE
#undef CONFIG_PKG_TINYLOGIN
#undef CONFIG_PKG_TINYPROXY
#define CONFIG_PKG_TSLIB 1
#undef CONFIG_PKG_TUNCTL
#define CONFIG_PKG_USBUTILS 1
#undef CONFIG_PKG_UCLINUX_CKSUM
#define CONFIG_PKG_UTIL_LINUX 1
#undef CONFIG_PKG_U_BOOT_TOOLS
#undef CONFIG_PKG_UNIFDEF
#define CONFIG_PKG_UNZIP 1
#undef CONFIG_PKG_VIM
#undef CONFIG_PKG_VPLAY
#undef CONFIG_PKG_VSFTPD
#undef CONFIG_PKG_WATCHDOG
#define CONFIG_PKG_WGET 1
#undef CONFIG_PKG_WHICH
#undef CONFIG_PKG_WIRELESS_TOOLS
#undef CONFIG_PKG_XFSPROGS

/*
 * X11
 */
#define CONFIG_X11_NONE 1
#undef CONFIG_PKG_XORG_SERVER

/*
 * X11 libraries and support packages
 */
#define CONFIG_PKG_RANDRPROTO 1
#define CONFIG_PKG_RENDERPROTO 1
#define CONFIG_PKG_FIXESPROTO 1
#define CONFIG_PKG_DAMAGEPROTO 1
#define CONFIG_PKG_XF86DRIPROTO 1
#define CONFIG_PKG_XCMISCPROTO 1
#define CONFIG_PKG_XEXTPROTO 1
#define CONFIG_PKG_XPROTO 1
#define CONFIG_PKG_SCRNSAVERPROTO 1
#define CONFIG_PKG_BIGREQSPROTO 1
#define CONFIG_PKG_RESOURCEPROTO 1
#define CONFIG_PKG_FONTSPROTO 1
#define CONFIG_PKG_INPUTPROTO 1
#define CONFIG_PKG_KBPROTO 1
#define CONFIG_PKG_VIDEOPROTO 1
#define CONFIG_PKG_COMPOSITEPROTO 1
#define CONFIG_PKG_RECORDPROTO 1
#define CONFIG_PKG_FONTCACHEPROTO 1
#define CONFIG_PKG_XF86BIGFONTPROTO 1
#define CONFIG_PKG_XCB_PROTO 1
#define CONFIG_PKG_LIBPTHREAD_STUBS 1
#define CONFIG_PKG_LIBFONTENC 1
#define CONFIG_PKG_XTRANS 1
#define CONFIG_PKG_LIBDRM 1
#define CONFIG_PKG_PIXMAN 1
#define CONFIG_PKG_LIBXCB 1
#define CONFIG_PKG_LIBXKBFILE 1
#define CONFIG_PKG_LIBXFONT 1
#define CONFIG_PKG_LIBXDMCP 1
#define CONFIG_PKG_LIBXAU 1
#define CONFIG_PKG_LIBX11 1
#define CONFIG_PKG_LIBXEXT 1
#define CONFIG_PKG_LIBXRENDER 1
#define CONFIG_PKG_LIBICE 1
#define CONFIG_PKG_LIBSM 1
#undef CONFIG_PKG_LIBXPM
#define CONFIG_PKG_LIBXT 1
#define CONFIG_PKG_LIBXMU 1
#undef CONFIG_PKG_LIBXAW
#define CONFIG_PKG_LIBXI 1
#define CONFIG_PKG_LIBXFIXES 1
#undef CONFIG_PKG_LIBXFT
#define CONFIG_PKG_LIBXCURSOR 1
#undef CONFIG_PKG_LIBXTST
#undef CONFIG_PKG_LIBXXF86DGA
#undef CONFIG_PKG_XKEYBOARD_CONFIG
#undef CONFIG_PKG_XORG_X11_XKB_UTILS
#undef CONFIG_PKG_XORG_X11_SERVER_UTILS
#undef CONFIG_PKG_YAFFS_UTILS
#undef CONFIG_PKG_ZAPTEL
#define CONFIG_PKG_ZLIB 1

/*
 * Additional Package selection
 */

/*
 * Target System Configuration
 */

/*
 * Options
 */
#define CONFIG_SYSCFG_HOSTNAME "nxp"
#define CONFIG_SYSCFG_WANT_LOGIN_TTY 1
#define CONFIG_SYSCFG_LOGING_TTY "::respawn:-/sbin/getty -L console 0 screen"
#define CONFIG_SYSCFG_MODLIST ""
#define CONFIG_SYSCFG_START_UDEV 1
#define CONFIG_SYSCFG_START_NETWORK 1

/*
 * Network setup
 */

/*
 * 
 */
#define CONFIG_SYSCFG_IFACE0 1
#define CONFIG_SYSCFG_NET_INTERFACE0 "eth0"
#define CONFIG_SYSCFG_DHCPC0 1

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE1

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE2

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE3

/*
 * 
 */
#undef CONFIG_SYSCFG_IFACE4
#define CONFIG_SYSCFG_DHCPC_CMD "udhcpc -b -i "
#undef CONFIG_SYSCFG_SETTIME
#define CONFIG_SYSCFG_START_SYSLOG 1
#define CONFIG_SYSCFG_START_INETD 1
#define CONFIG_SYSCFG_INETD_ARGS ""
#define CONFIG_SYSCFG_START_DROPBEAR_SSH 1
#define CONFIG_SYSCFG_DROPBEAR_ARGS ""
#define CONFIG_SYSCFG_START_BOA 1
#define CONFIG_SYSCFG_BOA_ARGS "-c /etc"

/*
 * Target Image Generation
 */

/*
 * Options
 */

/*
 * Choose your root filesystem image type
 */
#define CONFIG_DEPLOYMENT_JFFS2 1
#undef CONFIG_DEPLOYMENT_YAFFS2
#undef CONFIG_DEPLOYMENT_RAMDISK
#undef CONFIG_DEPLOYMENT_CRAMFS
#undef CONFIG_DEPLOYMENT_INITRAMFS
#undef CONFIG_DEPLOYMENT_ROMFS
#undef CONFIG_DEPLOYMENT_NFS
#define CONFIG_SYSCFG_DEPLOYMENT_STYLE "JFFS2"
#undef CONFIG_WANT_POST_BUILD_SCRIPT
#define CONFIG_DEPLOYMENT_ERASE_BLOCK_SIZE "128"
#define CONFIG_DEPLOYMENT_JFFS2_PAD 1
#define CONFIG_DEPLOYMENT_JFFS2_IMAGE_SIZE "5120"
#undef CONFIG_SYSCFG_READONLY_FS
#define CONFIG_SYSCFG_TMPFS_SIZE "512k"
#define CONFIG_SYSCFG_RAM_DIRS "/tmp /var"
#define CONFIG_DEPLOYMENT_ROOTFS_DIR ""
#undef CONFIG_DEPLOYMENT_ROOTFS_KEEPSTAGE
#undef CONFIG_DEPLOYMENT_HL2SL
#define CONFIG_DEPLOYMENT_RM_DOCS 1
#define CONFIG_DEPLOYMENT_RM_BOOT 1
#define CONFIG_DEPLOYMENT_RM_USR_SRC 1
#define CONFIG_DEPLOYMENT_RM_USR_INCLUDE 1
#define CONFIG_DEPLOYMENT_RM_LOCALES 1
#define CONFIG_DEPLOYMENT_RM_USER_DIRS ""
#define CONFIG_DEPLOYMENT_RM_USER_FILES ""
#define CONFIG_DEPLOYMENT_RM_STATIC_LIBS 1
#define CONFIG_DEPLOYMENT_RM_RPMDB "/var/lib/rpm"
#define CONFIG_DEPLOYMENT_STRIP 1
#undef CONFIG_DEPLOYMENT_STRIP_MORE
#define CONFIG_ERASE_BLOCK_SIZE "64"
#define CONFIG_FLASH_SIZE_KB "8192"
#define CONFIG_CAP_UCLIBC 1
#define CONFIG_CAP_GLIBC 1
#define CONFIG_CAP_LFS_5_1 1
#define CONFIG_CAP_HAS_MMU 1
#define CONFIG_CAP_HAS_SHARED 1
#define CONFIG_PKG_GCC_NAME "nobuild"
#define CONFIG_SYSCFG_TMPFS "tmpfs"
#define CONFIG_INITTAB_LINE "::respawn:-/sbin/getty -L console 0 screen"
#define CONFIG_UCLIBC_DYNAMIC_LINKER "/lib/ld-uClibc.so.0"
#define CONFIG_GLIBC_DYNAMIC_LINKER "/lib/ld.so.1"
#define CONFIG_SYSCFG_BAUD "115200"
#define CONFIG_SYSCFG_CONSOLEDEV "ttyS0"
#define CONFIG_SYSCFG_BOOTLOADER "u-boot"
#define CONFIG_U_BOOT_IMAGE_TYPE "ppc"
#define CONFIG_SYSCFG_RUNKERNELADDR "0x0"
#define CONFIG_SYSCFG_LOADKERNELADDR "0x800000"
#define CONFIG_SYSCFG_LOADDTBADDR "0x9F0000"
#define CONFIG_SYSCFG_LOADRAMADDR "0xB00000"
#define CONFIG_SYSCFG_CUTARG "zImage"
#undef CONFIG_CAP_FSL_INT
#define CONFIG_LTIB_RELEASE "9.1.1"
